### ISSUE TITLE
universal schedule beaker's jobs

### ISSUE THREAD

**Issue by Pajinek** [SatelliteQE/GreenTea#2]
Add new model to taskomatic that it descends all jobs of schedule run. For example I want schedule jobs for plan "daily" with schedule run ID 1.

`python manage.py beaker schedule --schedule-daily --label=(daily, nightly,...)

All jobs will contain link to schedule run. On webui data will descend by this ID. currently it uses date for group of recipes and tasks.

**Comment by jhutar** [comment]
What is remaining here to do?

**Comment by Pajinek** [comment]
Only testing, it should work. I think that the documentation is missing in wiki.
