### ISSUE TITLE
graph for statistic of jobs

### ISSUE THREAD

**Issue by Pajinek** [SatelliteQE/GreenTea#3]
create and insert svg graph to jobs page.

**Comment by omaciel** [comment]
@Pajinek any chance you can drop a screenshot here? :) I'm curious hehehe

**Comment by Pajinek** [comment]
@omaciel  I created first screenshot without private data https://github.com/SatelliteQE/GreenTea/wiki#screenshots

**Comment by omaciel** [comment]
You rock @Pajinek !!! :+1:

**Comment by rplevka** [comment]
@Pajinek :+1: 
I love D3 lib
